# Generated by Django 5.0.4 on 2024-04-07 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('half_length', models.IntegerField(help_text='Duration of each half in minutes')),
                ('substitution_interval', models.IntegerField(help_text='Interval for substitutions in minutes')),
                ('field_players_count', models.IntegerField(help_text='Number of players on the field at a time')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('Forward', 'Forward'), ('Centre', 'Centre'), ('Defence', 'Defence'), ('Goalie', 'Goalie')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('period', models.CharField(choices=[('first', 'First Half'), ('second', 'Second Half')], max_length=10)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.match')),
                ('player_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_substitutions', to='home.player')),
                ('player_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_substitutions', to='home.player')),
            ],
        ),
    ]
